PUSHING:

pipeline {
    agent any 
    
    stages {
        stage('checkout') {
            steps {
                git 'https://github.com/Revanth1616/dockerproject.git'
            }
        }
        stage('build') {
            steps {
                sh 'docker build -t $img .'
            }
        }
        stage('tag') {
            steps {
                sh 'docker tag $img $repo'
            }
        }
        stage('push') {
            steps {
                sh 'docker login -u revanth16 -p '
                sh 'docker push $repo'
            }
        }
    }
}


DEPLOYMENT:

pipeline {
    agent any

    stages {
        stage('check') {
            steps {
                git 'https://github.com/Revanth1616/dockerproject.git'
            }
        }
        stage('stack') {
            steps {
                sh 'docker stack deploy -c docker-compose.yml courses'
            }
        }
    }
}
